package it.cnr.si.cool.jconon.util;

public enum CallStato {
	PROCESSO_SCHEDE_ANONIME_CONCLUSO,
	PROCESSO_SCHEDE_ANONIME_CONCLUSO_COMMISSIONE_NON_ABILITATA,	
	PROCESSO_SCHEDE_ANONIME_ABILITATA_COMMISSIONE
}
