# DOCKER-VERSION 1.5.0
FROM      docker.si.cnr.it/centos-tomcat7
MAINTAINER Francesco Uliana <francesco.uliana@cnr.it>

RUN wget "http://maven.si.cnr.it/service/local/artifact/maven/redirect?r=releases&v=LATEST&g=it.cnr.si.cool.jconon&a=cool-jconon&e=war" -O /opt/apache-tomcat-7/webapps/jconon.war
