keycloak:
    enabled: true
    realm: cnr
    auth-server-url: http://dockerwebtest02.si.cnr.it:8110/auth
    ssl-required: NONE
    resource: selezioni
    public-client: false
    use-resource-role-mappings: true
    credentials:
        secret: secret
sso:
    cnr:
        user: is_cnr_user
        matricola: matricola_cnr
        livello: livello
        contesto: selezioni-app
        username_cnr: username_cnr
        logout_success_url: https://apps.cnr.it


spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
    main:
        # TODO - Workaround for circular dependency of KeycloakWebSecurityConfigurerAdapter https://github.com/keycloak/keycloak/issues/8857
        allow-circular-references: true
    session:
        hazelcast: